POST https://berry-oe8zzr3p.pai.tcloudbase.com/test
Content-Type: application/json

{
  "name": "leo"
}

###

GET https://berry-oe8zzr3p.pai.tcloudbase.com/test
Accept: application/json

###


POST http://localhost:3000/test
Content-Type: application/json

{
  "name": "leo"
}

###

GET http://localhost:3000/test
Accept: application/json

###